pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('00-foundations/app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                  docker build \
                    -t foundations-app:ci \
                    -f 02-docker/Dockerfile .
                '''
            }
        }
    }
stage('Push to Docker Hub') {
    steps {
        script {
            withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker tag foundations-app:ci $DOCKER_USER/foundations-app:ci
                    docker push $DOCKER_USER/foundations-app:ci
                """
            }
        }
    }
}
      post {
        success {
            echo 'CI passed and Docker image built'
        }
        failure {
            echo 'Pipeline failed before Docker packaging'
        }
    }
}

