pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    environment {
        IMAGE_NAME = "foundations-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "398995119442"
        ECR_REPO = "bootcamp-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Application') {
            steps {
                dir('00-foundations/app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build \
                    --platform linux/amd64 \
                    -t ${IMAGE_NAME}:${IMAGE_TAG} \
                    -f 02-docker/Dockerfile .
                """
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-bootcamp'
                ]]) {
                    sh """
                        aws ecr describe-repositories \
                        --repository-name ${ECR_REPO} \
                        --region ${AWS_REGION} || \
                        aws ecr create-repository \
                        --repository-name ${ECR_REPO} \
                        --region ${AWS_REGION}

                        aws ecr get-login-password --region ${AWS_REGION} | \
                        docker login --username AWS \
                        --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Tag & Push to ECR') {
            steps {
                sh """
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

                    docker push \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }
    }
    stage('Deploy to EKS') {
    steps {
        withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-bootcamp'
        ]])
        {
            sh """
                echo "Updating kubeconfig..."
                aws eks update-kubeconfig \
                  --region ${AWS_REGION} \
                  --name bootcamp-eks

                echo "Verifying cluster access..."
                kubectl get nodes

                echo "Updating deployment image..."
                kubectl set image deployment/bootcamp-app \
                  bootcamp-container=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG} \
                  -n bootcamp

                echo "Waiting for rollout..."
                kubectl rollout status deployment/bootcamp-app -n bootcamp
            """
        }
    }
}
    post {
        success {
            echo 'CI passed and image pushed to ECR successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
