pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('00-foundations/app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                  docker build \
                    -t foundations-app:ci \
                    -f 02-docker/Dockerfile .
                '''
            }
        }
    }

    post {
        success {
            echo 'CI passed and Docker image built'
        }
        failure {
            echo 'Pipeline failed before Docker packaging'
        }
    }
}

